services:
  factionwars:
    image: ghcr.io/thequib/factions:latest
    container_name: factions
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./factions.db:/app/factions.db
      - ./sprites:/app/sprites
    restart: unless-stopped
